### ISSUE TITLE
Bug: Miniplaceholder 3.0.1 not supported

### ISSUE THREAD

**Issue by sasha2002** [FancyMcPlugins/fancyplugins#108]
### In which plugin has the error occurred?

FancyHolograms

### What happened?

Both Holo and NPC are not correctly working with Miniplaceholder 3.0.1

### In which software has the error occurred?

Paper

### Plugin version

2.7.0

### Server version

1.21.7

### Relevant log output

```shell
[07:49:56 WARN]: [ChatColorHandler] Failed to combine resolver: 
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.tag.resolver.TagResolver io.github.miniplaceholders.api.MiniPlaceholders.getAudienceGlobalPlaceholders(net.kyori.adventure.audience.Audience)'
  at FancyHolograms-2.7.0.jar/de.oliver.fancyholograms.libs.chatcolorhandler.parsers.custom.MiniPlaceholdersParser.getResolver(MiniPlaceholdersParser.java:27) ~[FancyHolograms-2.7.0.jar:?]
  at FancyHolograms-2.7.0.jar/de.oliver.fancyholograms.libs.chatcolorhandler.parsers.Resolver.combineResolvers(Resolver.java:29) ~[FancyHolograms-2.7.0.jar:?]
  at FancyHolograms-2.7.0.jar/de.oliver.fancyholograms.libs.chatcolorhandler.ModernChatColorHandler.translate(ModernChatColorHandler.java:65) ~[FancyHolograms-2.7.0.jar:?]
  at FancyHolograms-2.7.0.jar/de.oliver.fancyholograms.libs.chatcolorhandler.ModernChatColorHandler.translate(ModernChatColorHandler.java:46) ~[FancyHolograms-2.7.0.jar:?]
  at FancyHolograms-2.7.0.jar/de.oliver.fancyholograms.api.hologram.Hologram.getShownText(Hologram.java:358) ~[FancyHolograms-2.7.0.jar:?]
  at FancyHolograms-2.7.0.jar/de.oliver.fancyholograms.hologram.version.HologramImpl.refresh(HologramImpl.java:207) ~[FancyHolograms-2.7.0.jar:?]
  at FancyHolograms-2.7.0.jar/de.oliver.fancyholograms.api.hologram.Hologram.refreshHologram(Hologram.java:228) ~[FancyHolograms-2.7.0.jar:?]
  at FancyHolograms-2.7.0.jar/de.oliver.fancyholograms.hologram.version.HologramImpl.show(HologramImpl.java:160) ~[FancyHolograms-2.7.0.jar:?]
  at FancyHolograms-2.7.0.jar/de.oliver.fancyholograms.api.hologram.Hologram.forceUpdateShownStateFor(Hologram.java:320) ~[FancyHolograms-2.7.0.jar:?]
  at FancyHolograms-2.7.0.jar/de.oliver.fancyholograms.HologramManagerImpl.lambda$initializeTasks$5(HologramManagerImpl.java:193) ~[FancyHolograms-2.7.0.jar:?]
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
  at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
  at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]



[07:44:26 WARN]: [ChatColorHandler] Failed to combine resolver:                                                                                                                                                                                                                                                              java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.tag.resolver.TagResolver io.github.miniplaceholders.api.MiniPlaceholders.getAudienceGlobalPlaceholders(net.kyori.adventure.audience.Audience)'                                                                                                                    at FancyNpcs-2.7.1.jar/de.oliver.fancynpcs.libs.chatcolorhandler.parsers.custom.MiniPlaceholdersParser.getResolver(MiniPlaceholdersParser.java:27) ~[FancyNpcs-2.7.1.jar:?]                                                                                                                                                  at FancyNpcs-2.7.1.jar/de.oliver.fancynpcs.libs.chatcolorhandler.parsers.Resolver.combineResolvers(Resolver.java:29) ~[FancyNpcs-2.7.1.jar:?]                                                                                                                                                                                at FancyNpcs-2.7.1.jar/de.oliver.fancynpcs.libs.chatcolorhandler.ModernChatColorHandler.translate(ModernChatColorHandler.java:65) ~[FancyNpcs-2.7.1.jar:?]                                                                                                                                                                   at FancyNpcs-2.7.1.jar/de.oliver.fancynpcs.libs.chatcolorhandler.ModernChatColorHandler.translate(ModernChatColorHandler.java:46) ~[FancyNpcs-2.7.1.jar:?]                                                                                                                                                                   at FancyNpcs-2.7.1.jar/de.oliver.fancynpcs.v1_21_6.Npc_1_21_6.update(Npc_1_21_6.java:232) ~[FancyNpcs-2.7.1.jar:?]                                                                                                                                                                                                           at FancyNpcs-2.7.1.jar/de.oliver.fancynpcs.api.Npc.updateForAll(Npc.java:125) ~[FancyNpcs-2.7.1.jar:?]                                                                                                                                                                                                                       at FancyHolograms-2.7.0.jar/de.oliver.fancyholograms.HologramManagerImpl.syncHologramWithNpc(HologramManagerImpl.java:309) ~[FancyHolograms-2.7.0.jar:?]                                                                                                                                                                     at FancyHolograms-2.7.0.jar/de.oliver.fancyholograms.commands.hologram.LinkWithNpcCMD.run(LinkWithNpcCMD.java:51) ~[FancyHolograms-2.7.0.jar:?]                                                                                                                                                                              at FancyHolograms-2.7.0.jar/de.oliver.fancyholograms.commands.HologramCMD.edit(HologramCMD.java:327) ~[FancyHolograms-2.7.0.jar:?]                                                                                                                                                                                           at FancyHolograms-2.7.0.jar/de.oliver.fancyholograms.commands.HologramCMD.execute(HologramCMD.java:101) ~[FancyHolograms-2.7.0.jar:?]                                                                                                                                                                                        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:83) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]                                                                                                                                                                                                                   at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                               at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                               at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:105) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                          at net.minecraft.commands.Commands.performCommand(Commands.java:357) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                                   at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                                   at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2313) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$12(ServerGamePacketListenerImpl.java:2286) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                       at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                                                 at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                 at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1449) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                           at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                            at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                  at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1429) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1423) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                            at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                              at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1380) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1388) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                   at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1265) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                           at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.7.jar:1.21.7-32-e792779]                                                                                                                                                                                                        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
